# Generated by Django 3.0.7 on 2020-06-21 08:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
